<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="text_maze_game" nsURI="http://www.example.org/text_maze_game"
    nsPrefix="text_maze_game">
  <eSubpackages name="gameEntity" nsURI="com.schrodingdong.text_maze_game.gameEntity"
      nsPrefix="gameEntity">
    <eClassifiers xsi:type="ecore:EClass" name="Balcony" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Balcony"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Corridor" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Corridor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LivingRoom" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Living Room"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true" interface="true">
      <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="roomLocationInfo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
          eType="#//gameEntity/Item" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="neighbooringRooms" upperBound="-1"
          eType="#//gameEntity/Room"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hall" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Hall"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Key" eSuperTypes="#//gameEntity/Item">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Key"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Kitchen" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Kitchen"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bedroom" eSuperTypes="#//gameEntity/Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Bedroom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Player">
      <eOperations name="pickItems"/>
      <eOperations name="move">
        <eParameters name="nextRoom" eType="#//gameEntity/Room"/>
      </eOperations>
      <eOperations name="useKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getNeighbooringRoomMap" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currRoom" lowerBound="1"
          eType="#//gameEntity/Room"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//gameEntity/Key"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
          eType="#//gameEntity/Item"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true" interface="true">
      <eOperations name="getName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="House">
      <eStructuralFeatures xsi:type="ecore:EReference" name="room" upperBound="-1"
          eType="#//gameEntity/Room" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//gameEntity/Player"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="gameLogic" nsURI="com.schrodingdong.text_maze_game.gameLogic"
      nsPrefix="gameLo">
    <eClassifiers xsi:type="ecore:EClass" name="Game">
      <eOperations name="startGame"/>
      <eOperations name="init">
        <eParameters name="p" eType="#//gameEntity/Player"/>
        <eParameters name="startRoom" eType="#//gameEntity/Room"/>
        <eParameters name="rooms" eType="#//gameLogic/collection"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
          eType="#//gameLogic/Action" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//gameEntity/Player"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="houseRooms" upperBound="-1"
          eType="#//gameEntity/Room"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scanner" eType="#//gameLogic/Scanner"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gameFlag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ItemCheck" eSuperTypes="#//gameLogic/Action">
      <eOperations name="doAction">
        <eParameters name="scanner" eType="#//gameLogic/Scanner"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NavigationCheck" eSuperTypes="#//gameLogic/Action">
      <eOperations name="doAction">
        <eParameters name="scanner" eType="#//gameLogic/Scanner"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExitCheck" eSuperTypes="#//gameLogic/Action">
      <eOperations name="doAction">
        <eParameters name="scanner" eType="#//gameLogic/Scanner"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eOperations name="doAction">
        <eParameters name="scanner" eType="#//gameLogic/Scanner"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="gameInstance" eType="#//gameLogic/Game"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Scanner" instanceClassName="java.util.Scanner"/>
    <eClassifiers xsi:type="ecore:EDataType" name="collection" instanceClassName="java.util.Collection"/>
  </eSubpackages>
</ecore:EPackage>
